### ISSUE TITLE
qtpy

### ISSUE THREAD

**Issue by jacobwilliams** [agoose77/qt-jsonschema-form#3]
Might consider using [qtpy](https://github.com/spyder-ide/qtpy), rather than hard coding PyQt5. That way, it would work with PyQt5, PySide2, PyQt6, and PySide6.

Should be as easy as replacing:

```python
from PyQt5 import QtWidgets, QtCore, QtGui
```

with:

```python
from qtpy import QtWidgets, QtCore, QtGui
```

**Comment by agoose77** [comment]
Sure! My workload's a bit nuts at the moment. If you make a PR, I'd be happy to review it!
